/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package continuous.integration;

public class App {
    public static void main(String[] args) {
        try {
            ContinuousIntegrationServer.startServer(8080);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
